### ISSUE TITLE
Update for Blender 4.1

### ISSUE THREAD

**Issue by Anthony-CamembearGames** [cubiest/bmesh-to-raw#5]
Hi,

I tried importing the addon in blender 4.1 and it wont show in the addon list afterwards,

Any idea on how I can make it work ?

Thanks :)

**Comment by MJacred** [comment]
I just tested with Blender 4.1.1 and it shows up.  
Did you install it via the Blender Preferences? Did Blender show you any errors?

![image](https://github.com/cubiest/bmesh-map/assets/6639237/5af1df56-cd2b-4ea8-996b-5413522bf255)

**Comment by MJacred** [comment]
Closing due to lack of response and not reproducible
